// <auto-generated />
using System;
using Api.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20220316142743_InitializeDb")]
    partial class InitializeDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Ciudad Autónoma de Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Río de Janeiro"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "São Paulo"
                        });
                });

            modelBuilder.Entity("Api.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Brasil"
                        });
                });

            modelBuilder.Entity("Api.Entities.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Humidity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RainChance")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TempC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TempF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Wind")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)41,
                            RainChance = (byte)2,
                            TempC = 32.9m,
                            TempF = 91.3m,
                            Wind = 17.5m
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)68,
                            RainChance = (byte)12,
                            TempC = -15.2m,
                            TempF = 4.6m,
                            Wind = 19.9m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)62,
                            RainChance = (byte)23,
                            TempC = -36.8m,
                            TempF = -34.2m,
                            Wind = 14.4m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)87,
                            RainChance = (byte)24,
                            TempC = -34.8m,
                            TempF = -30.6m,
                            Wind = 0.5m
                        },
                        new
                        {
                            Id = 9,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)59,
                            RainChance = (byte)86,
                            TempC = -21.3m,
                            TempF = -6.4m,
                            Wind = 19.1m
                        },
                        new
                        {
                            Id = 10,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)8,
                            RainChance = (byte)44,
                            TempC = -19.8m,
                            TempF = -3.7m,
                            Wind = 9.9m
                        },
                        new
                        {
                            Id = 11,
                            CityId = 1,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)47,
                            RainChance = (byte)19,
                            TempC = -21.8m,
                            TempF = -7.2m,
                            Wind = 2.4m
                        },
                        new
                        {
                            Id = 12,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)18,
                            RainChance = (byte)15,
                            TempC = 5.9m,
                            TempF = 42.7m,
                            Wind = 12.7m
                        },
                        new
                        {
                            Id = 13,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)29,
                            RainChance = (byte)72,
                            TempC = -44.2m,
                            TempF = -47.6m,
                            Wind = 3.1m
                        },
                        new
                        {
                            Id = 14,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)70,
                            RainChance = (byte)19,
                            TempC = 10.7m,
                            TempF = 51.3m,
                            Wind = 11.3m
                        },
                        new
                        {
                            Id = 15,
                            CityId = 1,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)38,
                            RainChance = (byte)12,
                            TempC = 27.8m,
                            TempF = 82.1m,
                            Wind = 3.5m
                        },
                        new
                        {
                            Id = 16,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)82,
                            RainChance = (byte)11,
                            TempC = 45.8m,
                            TempF = 114.4m,
                            Wind = 8.3m
                        },
                        new
                        {
                            Id = 17,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)49,
                            RainChance = (byte)95,
                            TempC = 8.5m,
                            TempF = 47.4m,
                            Wind = 13.5m
                        },
                        new
                        {
                            Id = 18,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)68,
                            RainChance = (byte)70,
                            TempC = 26.5m,
                            TempF = 79.8m,
                            Wind = 7.4m
                        },
                        new
                        {
                            Id = 19,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)52,
                            RainChance = (byte)52,
                            TempC = -35.1m,
                            TempF = -31.1m,
                            Wind = 12.3m
                        },
                        new
                        {
                            Id = 20,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)84,
                            RainChance = (byte)70,
                            TempC = 35.3m,
                            TempF = 95.6m,
                            Wind = 18.8m
                        },
                        new
                        {
                            Id = 21,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)28,
                            RainChance = (byte)8,
                            TempC = 47.5m,
                            TempF = 117.5m,
                            Wind = 3.1m
                        },
                        new
                        {
                            Id = 22,
                            CityId = 1,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)26,
                            RainChance = (byte)80,
                            TempC = 33.2m,
                            TempF = 91.7m,
                            Wind = 2.0m
                        },
                        new
                        {
                            Id = 23,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)52,
                            RainChance = (byte)99,
                            TempC = -46.1m,
                            TempF = -51.0m,
                            Wind = 14.5m
                        },
                        new
                        {
                            Id = 24,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)40,
                            RainChance = (byte)24,
                            TempC = -8.5m,
                            TempF = 16.7m,
                            Wind = 5.5m
                        },
                        new
                        {
                            Id = 25,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)62,
                            RainChance = (byte)98,
                            TempC = -23.3m,
                            TempF = -9.9m,
                            Wind = 17.8m
                        },
                        new
                        {
                            Id = 26,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)56,
                            RainChance = (byte)87,
                            TempC = -7.6m,
                            TempF = 18.4m,
                            Wind = 12.8m
                        },
                        new
                        {
                            Id = 27,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)24,
                            RainChance = (byte)87,
                            TempC = 11.2m,
                            TempF = 52.2m,
                            Wind = 18.7m
                        },
                        new
                        {
                            Id = 28,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)76,
                            RainChance = (byte)35,
                            TempC = -27.2m,
                            TempF = -16.9m,
                            Wind = 3.1m
                        },
                        new
                        {
                            Id = 29,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)45,
                            RainChance = (byte)92,
                            TempC = -37.0m,
                            TempF = -34.6m,
                            Wind = 6.7m
                        },
                        new
                        {
                            Id = 30,
                            CityId = 1,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)99,
                            RainChance = (byte)26,
                            TempC = 24.6m,
                            TempF = 76.3m,
                            Wind = 9.8m
                        },
                        new
                        {
                            Id = 31,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)73,
                            RainChance = (byte)8,
                            TempC = 39.3m,
                            TempF = 102.7m,
                            Wind = 5.6m
                        },
                        new
                        {
                            Id = 32,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)71,
                            RainChance = (byte)28,
                            TempC = -5.7m,
                            TempF = 21.8m,
                            Wind = 14.8m
                        },
                        new
                        {
                            Id = 33,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)40,
                            RainChance = (byte)94,
                            TempC = 9.8m,
                            TempF = 49.6m,
                            Wind = 9.9m
                        },
                        new
                        {
                            Id = 34,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)20,
                            RainChance = (byte)45,
                            TempC = 16.1m,
                            TempF = 61.0m,
                            Wind = 1.7m
                        },
                        new
                        {
                            Id = 35,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)13,
                            RainChance = (byte)9,
                            TempC = 45.3m,
                            TempF = 113.5m,
                            Wind = 9.9m
                        },
                        new
                        {
                            Id = 36,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)56,
                            RainChance = (byte)75,
                            TempC = -2.2m,
                            TempF = 28.1m,
                            Wind = 17.6m
                        },
                        new
                        {
                            Id = 37,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)42,
                            RainChance = (byte)54,
                            TempC = 11.1m,
                            TempF = 51.9m,
                            Wind = 14.2m
                        },
                        new
                        {
                            Id = 38,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)19,
                            RainChance = (byte)55,
                            TempC = -14.5m,
                            TempF = 5.8m,
                            Wind = 8.4m
                        },
                        new
                        {
                            Id = 39,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)55,
                            RainChance = (byte)80,
                            TempC = 13.0m,
                            TempF = 55.3m,
                            Wind = 2.1m
                        },
                        new
                        {
                            Id = 40,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)76,
                            RainChance = (byte)58,
                            TempC = 20.8m,
                            TempF = 69.4m,
                            Wind = 15.0m
                        },
                        new
                        {
                            Id = 41,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)98,
                            RainChance = (byte)3,
                            TempC = -7.5m,
                            TempF = 18.4m,
                            Wind = 16.4m
                        },
                        new
                        {
                            Id = 42,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)14,
                            RainChance = (byte)59,
                            TempC = 28.3m,
                            TempF = 83.0m,
                            Wind = 3.4m
                        },
                        new
                        {
                            Id = 43,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)33,
                            RainChance = (byte)71,
                            TempC = -28.1m,
                            TempF = -18.6m,
                            Wind = 11.7m
                        },
                        new
                        {
                            Id = 44,
                            CityId = 2,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)26,
                            RainChance = (byte)91,
                            TempC = 14.6m,
                            TempF = 58.2m,
                            Wind = 17.9m
                        },
                        new
                        {
                            Id = 45,
                            CityId = 2,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)3,
                            RainChance = (byte)56,
                            TempC = 35.7m,
                            TempF = 96.2m,
                            Wind = 2.0m
                        },
                        new
                        {
                            Id = 46,
                            CityId = 2,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)92,
                            RainChance = (byte)23,
                            TempC = 16.7m,
                            TempF = 62.1m,
                            Wind = 11.3m
                        },
                        new
                        {
                            Id = 47,
                            CityId = 2,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)74,
                            RainChance = (byte)75,
                            TempC = 6.6m,
                            TempF = 43.8m,
                            Wind = 9.0m
                        },
                        new
                        {
                            Id = 48,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)79,
                            RainChance = (byte)71,
                            TempC = 17.8m,
                            TempF = 64.1m,
                            Wind = 0.6m
                        },
                        new
                        {
                            Id = 49,
                            CityId = 2,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)4,
                            RainChance = (byte)63,
                            TempC = 24.9m,
                            TempF = 76.7m,
                            Wind = 11.2m
                        },
                        new
                        {
                            Id = 50,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)65,
                            RainChance = (byte)54,
                            TempC = 40.9m,
                            TempF = 105.6m,
                            Wind = 0.4m
                        },
                        new
                        {
                            Id = 51,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)70,
                            RainChance = (byte)85,
                            TempC = 30.7m,
                            TempF = 87.3m,
                            Wind = 19.0m
                        },
                        new
                        {
                            Id = 52,
                            CityId = 2,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)66,
                            RainChance = (byte)21,
                            TempC = 46.4m,
                            TempF = 115.4m,
                            Wind = 10.4m
                        },
                        new
                        {
                            Id = 53,
                            CityId = 2,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)95,
                            RainChance = (byte)60,
                            TempC = -49.3m,
                            TempF = -56.7m,
                            Wind = 13.0m
                        },
                        new
                        {
                            Id = 54,
                            CityId = 2,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)14,
                            RainChance = (byte)80,
                            TempC = -20.3m,
                            TempF = -4.5m,
                            Wind = 18.6m
                        },
                        new
                        {
                            Id = 55,
                            CityId = 2,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)95,
                            RainChance = (byte)19,
                            TempC = -35.5m,
                            TempF = -31.8m,
                            Wind = 18.4m
                        },
                        new
                        {
                            Id = 56,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)27,
                            RainChance = (byte)86,
                            TempC = 40.6m,
                            TempF = 105.1m,
                            Wind = 12.7m
                        },
                        new
                        {
                            Id = 57,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)59,
                            RainChance = (byte)47,
                            TempC = -48.3m,
                            TempF = -55.0m,
                            Wind = 4.8m
                        },
                        new
                        {
                            Id = 58,
                            CityId = 2,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)50,
                            RainChance = (byte)43,
                            TempC = -34.1m,
                            TempF = -29.4m,
                            Wind = 15.8m
                        },
                        new
                        {
                            Id = 59,
                            CityId = 2,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)26,
                            RainChance = (byte)62,
                            TempC = -43.4m,
                            TempF = -46.1m,
                            Wind = 11.6m
                        },
                        new
                        {
                            Id = 60,
                            CityId = 2,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)99,
                            RainChance = (byte)86,
                            TempC = 1.7m,
                            TempF = 35.1m,
                            Wind = 6.6m
                        },
                        new
                        {
                            Id = 61,
                            CityId = 2,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)49,
                            RainChance = (byte)11,
                            TempC = -46.3m,
                            TempF = -51.4m,
                            Wind = 6.2m
                        },
                        new
                        {
                            Id = 62,
                            CityId = 2,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)28,
                            RainChance = (byte)34,
                            TempC = -40.5m,
                            TempF = -41.0m,
                            Wind = 8.0m
                        },
                        new
                        {
                            Id = 63,
                            CityId = 2,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)76,
                            RainChance = (byte)19,
                            TempC = -35.2m,
                            TempF = -31.4m,
                            Wind = 19.8m
                        },
                        new
                        {
                            Id = 64,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)98,
                            RainChance = (byte)97,
                            TempC = 18.8m,
                            TempF = 65.9m,
                            Wind = 17.2m
                        },
                        new
                        {
                            Id = 65,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)89,
                            RainChance = (byte)51,
                            TempC = 34.7m,
                            TempF = 94.5m,
                            Wind = 2.8m
                        },
                        new
                        {
                            Id = 66,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)87,
                            RainChance = (byte)49,
                            TempC = 5.0m,
                            TempF = 41.1m,
                            Wind = 3.0m
                        },
                        new
                        {
                            Id = 67,
                            CityId = 3,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)96,
                            RainChance = (byte)65,
                            TempC = 0.1m,
                            TempF = 32.2m,
                            Wind = 0.6m
                        },
                        new
                        {
                            Id = 68,
                            CityId = 3,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)5,
                            RainChance = (byte)15,
                            TempC = -26.1m,
                            TempF = -14.9m,
                            Wind = 12.0m
                        },
                        new
                        {
                            Id = 69,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)9,
                            RainChance = (byte)48,
                            TempC = 8.6m,
                            TempF = 47.5m,
                            Wind = 10.6m
                        },
                        new
                        {
                            Id = 70,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)70,
                            RainChance = (byte)2,
                            TempC = -17.6m,
                            TempF = 0.4m,
                            Wind = 0.7m
                        },
                        new
                        {
                            Id = 71,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)27,
                            RainChance = (byte)5,
                            TempC = 20.4m,
                            TempF = 68.6m,
                            Wind = 8.1m
                        },
                        new
                        {
                            Id = 72,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)12,
                            RainChance = (byte)58,
                            TempC = -36.2m,
                            TempF = -33.2m,
                            Wind = 7.8m
                        },
                        new
                        {
                            Id = 73,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)79,
                            RainChance = (byte)49,
                            TempC = -38.3m,
                            TempF = -37.0m,
                            Wind = 3.2m
                        },
                        new
                        {
                            Id = 74,
                            CityId = 3,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)52,
                            RainChance = (byte)93,
                            TempC = 40.3m,
                            TempF = 104.5m,
                            Wind = 0.6m
                        },
                        new
                        {
                            Id = 75,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)59,
                            RainChance = (byte)73,
                            TempC = 25.5m,
                            TempF = 77.8m,
                            Wind = 15.7m
                        },
                        new
                        {
                            Id = 76,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)84,
                            RainChance = (byte)32,
                            TempC = -31.0m,
                            TempF = -23.8m,
                            Wind = 11.6m
                        },
                        new
                        {
                            Id = 77,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)23,
                            RainChance = (byte)21,
                            TempC = 37.9m,
                            TempF = 100.3m,
                            Wind = 8.0m
                        },
                        new
                        {
                            Id = 78,
                            CityId = 3,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)23,
                            RainChance = (byte)73,
                            TempC = -36.1m,
                            TempF = -32.9m,
                            Wind = 18.1m
                        },
                        new
                        {
                            Id = 79,
                            CityId = 3,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)45,
                            RainChance = (byte)98,
                            TempC = 26.6m,
                            TempF = 79.9m,
                            Wind = 8.6m
                        },
                        new
                        {
                            Id = 80,
                            CityId = 3,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)40,
                            RainChance = (byte)92,
                            TempC = -34.6m,
                            TempF = -30.2m,
                            Wind = 0.5m
                        },
                        new
                        {
                            Id = 81,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)6,
                            RainChance = (byte)47,
                            TempC = -42.5m,
                            TempF = -44.6m,
                            Wind = 10.6m
                        },
                        new
                        {
                            Id = 82,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)37,
                            RainChance = (byte)19,
                            TempC = 20.7m,
                            TempF = 69.3m,
                            Wind = 0.3m
                        },
                        new
                        {
                            Id = 83,
                            CityId = 3,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)59,
                            RainChance = (byte)99,
                            TempC = 7.4m,
                            TempF = 45.2m,
                            Wind = 1.9m
                        },
                        new
                        {
                            Id = 84,
                            CityId = 3,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)31,
                            RainChance = (byte)87,
                            TempC = -47.0m,
                            TempF = -52.6m,
                            Wind = 15.2m
                        },
                        new
                        {
                            Id = 85,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)16,
                            RainChance = (byte)69,
                            TempC = -29.5m,
                            TempF = -21.0m,
                            Wind = 13.3m
                        },
                        new
                        {
                            Id = 86,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)18,
                            RainChance = (byte)80,
                            TempC = 2.5m,
                            TempF = 36.5m,
                            Wind = 6.1m
                        },
                        new
                        {
                            Id = 87,
                            CityId = 3,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)77,
                            RainChance = (byte)56,
                            TempC = -41.9m,
                            TempF = -43.4m,
                            Wind = 0.8m
                        },
                        new
                        {
                            Id = 88,
                            CityId = 3,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)8,
                            RainChance = (byte)58,
                            TempC = -49.2m,
                            TempF = -56.5m,
                            Wind = 0.2m
                        },
                        new
                        {
                            Id = 89,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)0,
                            RainChance = (byte)3,
                            TempC = 0.5m,
                            TempF = 32.8m,
                            Wind = 1.4m
                        },
                        new
                        {
                            Id = 90,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)2,
                            RainChance = (byte)29,
                            TempC = 35.6m,
                            TempF = 96.0m,
                            Wind = 19.9m
                        },
                        new
                        {
                            Id = 91,
                            CityId = 3,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)72,
                            RainChance = (byte)92,
                            TempC = -23.4m,
                            TempF = -10.2m,
                            Wind = 18.7m
                        },
                        new
                        {
                            Id = 92,
                            CityId = 3,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)15,
                            RainChance = (byte)66,
                            TempC = -23.6m,
                            TempF = -10.5m,
                            Wind = 19.6m
                        },
                        new
                        {
                            Id = 93,
                            CityId = 3,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)99,
                            RainChance = (byte)11,
                            TempC = 16.2m,
                            TempF = 61.2m,
                            Wind = 19.3m
                        },
                        new
                        {
                            Id = 94,
                            CityId = 3,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)15,
                            RainChance = (byte)51,
                            TempC = 15.1m,
                            TempF = 59.1m,
                            Wind = 17.1m
                        },
                        new
                        {
                            Id = 95,
                            CityId = 4,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)4,
                            RainChance = (byte)78,
                            TempC = 34.3m,
                            TempF = 93.7m,
                            Wind = 7.6m
                        },
                        new
                        {
                            Id = 96,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)10,
                            RainChance = (byte)4,
                            TempC = -30.1m,
                            TempF = -22.3m,
                            Wind = 12.0m
                        },
                        new
                        {
                            Id = 97,
                            CityId = 4,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)73,
                            RainChance = (byte)44,
                            TempC = 28.8m,
                            TempF = 83.8m,
                            Wind = 15.7m
                        },
                        new
                        {
                            Id = 98,
                            CityId = 4,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)57,
                            RainChance = (byte)23,
                            TempC = -46.7m,
                            TempF = -52.1m,
                            Wind = 14.8m
                        },
                        new
                        {
                            Id = 99,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)47,
                            RainChance = (byte)88,
                            TempC = 10.0m,
                            TempF = 50.1m,
                            Wind = 19.6m
                        },
                        new
                        {
                            Id = 100,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)70,
                            RainChance = (byte)11,
                            TempC = -29.2m,
                            TempF = -20.6m,
                            Wind = 8.9m
                        },
                        new
                        {
                            Id = 101,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)85,
                            RainChance = (byte)45,
                            TempC = 4.3m,
                            TempF = 39.7m,
                            Wind = 8.4m
                        },
                        new
                        {
                            Id = 102,
                            CityId = 4,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)20,
                            RainChance = (byte)37,
                            TempC = 32.0m,
                            TempF = 89.6m,
                            Wind = 13.5m
                        },
                        new
                        {
                            Id = 103,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)8,
                            RainChance = (byte)35,
                            TempC = 35.5m,
                            TempF = 96.0m,
                            Wind = 15.5m
                        },
                        new
                        {
                            Id = 104,
                            CityId = 4,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)25,
                            RainChance = (byte)50,
                            TempC = -32.7m,
                            TempF = -26.8m,
                            Wind = 5.9m
                        },
                        new
                        {
                            Id = 105,
                            CityId = 4,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)19,
                            RainChance = (byte)87,
                            TempC = 32.7m,
                            TempF = 90.8m,
                            Wind = 2.0m
                        },
                        new
                        {
                            Id = 106,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)72,
                            RainChance = (byte)2,
                            TempC = -3.4m,
                            TempF = 25.9m,
                            Wind = 1.2m
                        },
                        new
                        {
                            Id = 107,
                            CityId = 4,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)4,
                            RainChance = (byte)56,
                            TempC = 37.5m,
                            TempF = 99.5m,
                            Wind = 10.9m
                        },
                        new
                        {
                            Id = 108,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)7,
                            RainChance = (byte)0,
                            TempC = 48.5m,
                            TempF = 119.3m,
                            Wind = 8.4m
                        },
                        new
                        {
                            Id = 109,
                            CityId = 4,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)95,
                            RainChance = (byte)38,
                            TempC = 7.0m,
                            TempF = 44.6m,
                            Wind = 18.7m
                        },
                        new
                        {
                            Id = 110,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)49,
                            RainChance = (byte)30,
                            TempC = -39.1m,
                            TempF = -38.4m,
                            Wind = 7.5m
                        },
                        new
                        {
                            Id = 111,
                            CityId = 4,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)53,
                            RainChance = (byte)31,
                            TempC = -34.3m,
                            TempF = -29.7m,
                            Wind = 11.5m
                        },
                        new
                        {
                            Id = 112,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)59,
                            RainChance = (byte)75,
                            TempC = -36.0m,
                            TempF = -32.7m,
                            Wind = 13.3m
                        },
                        new
                        {
                            Id = 113,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)1,
                            RainChance = (byte)26,
                            TempC = 49.2m,
                            TempF = 120.5m,
                            Wind = 1.5m
                        },
                        new
                        {
                            Id = 114,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)63,
                            RainChance = (byte)40,
                            TempC = -2.7m,
                            TempF = 27.1m,
                            Wind = 9.7m
                        },
                        new
                        {
                            Id = 115,
                            CityId = 4,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)17,
                            RainChance = (byte)43,
                            TempC = 49.0m,
                            TempF = 120.2m,
                            Wind = 17.0m
                        },
                        new
                        {
                            Id = 116,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)7,
                            RainChance = (byte)8,
                            TempC = -39.0m,
                            TempF = -38.3m,
                            Wind = 19.3m
                        },
                        new
                        {
                            Id = 117,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)99,
                            RainChance = (byte)92,
                            TempC = 27.1m,
                            TempF = 80.8m,
                            Wind = 14.2m
                        },
                        new
                        {
                            Id = 118,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)71,
                            RainChance = (byte)27,
                            TempC = 31.6m,
                            TempF = 88.9m,
                            Wind = 12.1m
                        },
                        new
                        {
                            Id = 119,
                            CityId = 4,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)54,
                            RainChance = (byte)9,
                            TempC = -36.7m,
                            TempF = -34.0m,
                            Wind = 12.0m
                        },
                        new
                        {
                            Id = 120,
                            CityId = 4,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)87,
                            RainChance = (byte)66,
                            TempC = 19.8m,
                            TempF = 67.6m,
                            Wind = 18.3m
                        },
                        new
                        {
                            Id = 121,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)68,
                            RainChance = (byte)44,
                            TempC = -8.8m,
                            TempF = 16.2m,
                            Wind = 19.6m
                        },
                        new
                        {
                            Id = 122,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)15,
                            RainChance = (byte)8,
                            TempC = 21.2m,
                            TempF = 70.1m,
                            Wind = 8.9m
                        },
                        new
                        {
                            Id = 123,
                            CityId = 4,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)69,
                            RainChance = (byte)70,
                            TempC = 30.9m,
                            TempF = 87.7m,
                            Wind = 1.7m
                        },
                        new
                        {
                            Id = 124,
                            CityId = 4,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)88,
                            RainChance = (byte)13,
                            TempC = -22.3m,
                            TempF = -8.1m,
                            Wind = 7.7m
                        });
                });

            modelBuilder.Entity("Api.Entities.City", b =>
                {
                    b.HasOne("Api.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Api.Entities.Weather", b =>
                {
                    b.HasOne("Api.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
