// <auto-generated />
using System;
using Api.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20220313175353_InitializeDb")]
    partial class InitializeDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Ciudad Autónoma de Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Río de Janeiro"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "São Paulo"
                        });
                });

            modelBuilder.Entity("Api.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Brasil"
                        });
                });

            modelBuilder.Entity("Api.Entities.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Humidity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RainChance")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TempC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TempF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Wind")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)78,
                            RainChance = (byte)32,
                            TempC = 19.4m,
                            TempF = 51.4m,
                            Wind = 17.9m
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)88,
                            RainChance = (byte)34,
                            TempC = 34.3m,
                            TempF = 66.3m,
                            Wind = 16.8m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)50,
                            RainChance = (byte)32,
                            TempC = 3.3m,
                            TempF = 35.3m,
                            Wind = 17.4m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)92,
                            RainChance = (byte)84,
                            TempC = 30.5m,
                            TempF = 62.5m,
                            Wind = 3.2m
                        },
                        new
                        {
                            Id = 9,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)13,
                            RainChance = (byte)98,
                            TempC = -1.1m,
                            TempF = 30.9m,
                            Wind = 1.4m
                        },
                        new
                        {
                            Id = 10,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)60,
                            RainChance = (byte)52,
                            TempC = 49.7m,
                            TempF = 81.7m,
                            Wind = 19.7m
                        },
                        new
                        {
                            Id = 11,
                            CityId = 1,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)64,
                            RainChance = (byte)7,
                            TempC = 45.0m,
                            TempF = 77.0m,
                            Wind = 8.5m
                        },
                        new
                        {
                            Id = 12,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)8,
                            RainChance = (byte)63,
                            TempC = -31.3m,
                            TempF = 0.7m,
                            Wind = 12.1m
                        },
                        new
                        {
                            Id = 13,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)60,
                            RainChance = (byte)80,
                            TempC = 12.9m,
                            TempF = 44.9m,
                            Wind = 0.8m
                        },
                        new
                        {
                            Id = 14,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)15,
                            RainChance = (byte)55,
                            TempC = -10.0m,
                            TempF = 22.0m,
                            Wind = 0.3m
                        },
                        new
                        {
                            Id = 15,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)78,
                            RainChance = (byte)16,
                            TempC = 7.4m,
                            TempF = 39.4m,
                            Wind = 11.1m
                        },
                        new
                        {
                            Id = 16,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)69,
                            RainChance = (byte)79,
                            TempC = -17.0m,
                            TempF = 15.0m,
                            Wind = 6.2m
                        },
                        new
                        {
                            Id = 17,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)85,
                            RainChance = (byte)54,
                            TempC = -45.4m,
                            TempF = -13.4m,
                            Wind = 6.0m
                        },
                        new
                        {
                            Id = 18,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)6,
                            RainChance = (byte)4,
                            TempC = -3.2m,
                            TempF = 28.8m,
                            Wind = 3.1m
                        },
                        new
                        {
                            Id = 19,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)83,
                            RainChance = (byte)77,
                            TempC = 44.3m,
                            TempF = 76.3m,
                            Wind = 17.8m
                        },
                        new
                        {
                            Id = 20,
                            CityId = 1,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)11,
                            RainChance = (byte)50,
                            TempC = 41.6m,
                            TempF = 73.6m,
                            Wind = 3.5m
                        },
                        new
                        {
                            Id = 21,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)35,
                            RainChance = (byte)20,
                            TempC = -47.5m,
                            TempF = -15.5m,
                            Wind = 5.4m
                        },
                        new
                        {
                            Id = 22,
                            CityId = 1,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)56,
                            RainChance = (byte)88,
                            TempC = 5.7m,
                            TempF = 37.7m,
                            Wind = 3.4m
                        },
                        new
                        {
                            Id = 23,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)33,
                            RainChance = (byte)38,
                            TempC = 21.6m,
                            TempF = 53.6m,
                            Wind = 12.5m
                        },
                        new
                        {
                            Id = 24,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)40,
                            RainChance = (byte)51,
                            TempC = 32.3m,
                            TempF = 64.3m,
                            Wind = 5.0m
                        },
                        new
                        {
                            Id = 25,
                            CityId = 1,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)12,
                            RainChance = (byte)11,
                            TempC = 2.0m,
                            TempF = 34.0m,
                            Wind = 14.6m
                        },
                        new
                        {
                            Id = 26,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)70,
                            RainChance = (byte)2,
                            TempC = -18.6m,
                            TempF = 13.4m,
                            Wind = 13.3m
                        },
                        new
                        {
                            Id = 27,
                            CityId = 1,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)53,
                            RainChance = (byte)22,
                            TempC = 46.2m,
                            TempF = 78.2m,
                            Wind = 8.1m
                        },
                        new
                        {
                            Id = 28,
                            CityId = 1,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)80,
                            RainChance = (byte)97,
                            TempC = 31.5m,
                            TempF = 63.5m,
                            Wind = 4.9m
                        },
                        new
                        {
                            Id = 29,
                            CityId = 1,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)25,
                            RainChance = (byte)93,
                            TempC = -13.6m,
                            TempF = 18.4m,
                            Wind = 11.1m
                        },
                        new
                        {
                            Id = 30,
                            CityId = 1,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)97,
                            RainChance = (byte)69,
                            TempC = 42.2m,
                            TempF = 74.2m,
                            Wind = 10.6m
                        },
                        new
                        {
                            Id = 31,
                            CityId = 1,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)54,
                            RainChance = (byte)38,
                            TempC = -34.2m,
                            TempF = -2.2m,
                            Wind = 17.6m
                        },
                        new
                        {
                            Id = 32,
                            CityId = 1,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)2,
                            RainChance = (byte)77,
                            TempC = 21.3m,
                            TempF = 53.3m,
                            Wind = 8.2m
                        },
                        new
                        {
                            Id = 33,
                            CityId = 1,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)89,
                            RainChance = (byte)40,
                            TempC = 39.5m,
                            TempF = 71.5m,
                            Wind = 1.2m
                        },
                        new
                        {
                            Id = 34,
                            CityId = 1,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)47,
                            RainChance = (byte)69,
                            TempC = 10.6m,
                            TempF = 42.6m,
                            Wind = 16.5m
                        },
                        new
                        {
                            Id = 35,
                            CityId = 2,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)41,
                            RainChance = (byte)47,
                            TempC = 49.1m,
                            TempF = 81.1m,
                            Wind = 11.1m
                        },
                        new
                        {
                            Id = 36,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)62,
                            RainChance = (byte)98,
                            TempC = 32.5m,
                            TempF = 64.5m,
                            Wind = 8.4m
                        },
                        new
                        {
                            Id = 37,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)50,
                            RainChance = (byte)68,
                            TempC = 32.7m,
                            TempF = 64.7m,
                            Wind = 3.0m
                        },
                        new
                        {
                            Id = 38,
                            CityId = 2,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)19,
                            RainChance = (byte)3,
                            TempC = 30.4m,
                            TempF = 62.4m,
                            Wind = 0.2m
                        },
                        new
                        {
                            Id = 39,
                            CityId = 2,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)5,
                            RainChance = (byte)61,
                            TempC = -7.0m,
                            TempF = 25.0m,
                            Wind = 9.8m
                        },
                        new
                        {
                            Id = 40,
                            CityId = 2,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)63,
                            RainChance = (byte)55,
                            TempC = -34.9m,
                            TempF = -2.9m,
                            Wind = 7.6m
                        },
                        new
                        {
                            Id = 41,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)47,
                            RainChance = (byte)41,
                            TempC = 9.9m,
                            TempF = 41.9m,
                            Wind = 13.0m
                        },
                        new
                        {
                            Id = 42,
                            CityId = 2,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)13,
                            RainChance = (byte)35,
                            TempC = -11.0m,
                            TempF = 21.0m,
                            Wind = 1.8m
                        },
                        new
                        {
                            Id = 43,
                            CityId = 2,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)51,
                            RainChance = (byte)25,
                            TempC = 34.9m,
                            TempF = 66.9m,
                            Wind = 4.9m
                        },
                        new
                        {
                            Id = 44,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)33,
                            RainChance = (byte)75,
                            TempC = 6.9m,
                            TempF = 38.9m,
                            Wind = 5.6m
                        },
                        new
                        {
                            Id = 45,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)10,
                            RainChance = (byte)79,
                            TempC = 41.3m,
                            TempF = 73.3m,
                            Wind = 14.1m
                        },
                        new
                        {
                            Id = 46,
                            CityId = 2,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)86,
                            RainChance = (byte)65,
                            TempC = -38.8m,
                            TempF = -6.8m,
                            Wind = 2.6m
                        },
                        new
                        {
                            Id = 47,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)91,
                            RainChance = (byte)66,
                            TempC = 45.8m,
                            TempF = 77.8m,
                            Wind = 11.2m
                        },
                        new
                        {
                            Id = 48,
                            CityId = 2,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)31,
                            RainChance = (byte)62,
                            TempC = 1.4m,
                            TempF = 33.4m,
                            Wind = 0.6m
                        },
                        new
                        {
                            Id = 49,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)53,
                            RainChance = (byte)34,
                            TempC = 9.3m,
                            TempF = 41.3m,
                            Wind = 9.1m
                        },
                        new
                        {
                            Id = 50,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)47,
                            RainChance = (byte)80,
                            TempC = -28.9m,
                            TempF = 3.1m,
                            Wind = 8.9m
                        },
                        new
                        {
                            Id = 51,
                            CityId = 2,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)47,
                            RainChance = (byte)34,
                            TempC = -3.8m,
                            TempF = 28.2m,
                            Wind = 12.9m
                        },
                        new
                        {
                            Id = 52,
                            CityId = 2,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)11,
                            RainChance = (byte)35,
                            TempC = -32.4m,
                            TempF = -0.4m,
                            Wind = 14.1m
                        },
                        new
                        {
                            Id = 53,
                            CityId = 2,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)59,
                            RainChance = (byte)57,
                            TempC = -25.8m,
                            TempF = 6.2m,
                            Wind = 4.9m
                        },
                        new
                        {
                            Id = 54,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)7,
                            RainChance = (byte)35,
                            TempC = 45.1m,
                            TempF = 77.1m,
                            Wind = 15.8m
                        },
                        new
                        {
                            Id = 55,
                            CityId = 2,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)73,
                            RainChance = (byte)83,
                            TempC = 10.4m,
                            TempF = 42.4m,
                            Wind = 0.9m
                        },
                        new
                        {
                            Id = 56,
                            CityId = 2,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)85,
                            RainChance = (byte)2,
                            TempC = 9.4m,
                            TempF = 41.4m,
                            Wind = 18.6m
                        },
                        new
                        {
                            Id = 57,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)16,
                            RainChance = (byte)1,
                            TempC = 5.7m,
                            TempF = 37.7m,
                            Wind = 16.5m
                        },
                        new
                        {
                            Id = 58,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)99,
                            RainChance = (byte)50,
                            TempC = 17.2m,
                            TempF = 49.2m,
                            Wind = 12.9m
                        },
                        new
                        {
                            Id = 59,
                            CityId = 2,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)9,
                            RainChance = (byte)70,
                            TempC = -24.7m,
                            TempF = 7.3m,
                            Wind = 10.4m
                        },
                        new
                        {
                            Id = 60,
                            CityId = 2,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)82,
                            RainChance = (byte)18,
                            TempC = -34.4m,
                            TempF = -2.4m,
                            Wind = 19.8m
                        },
                        new
                        {
                            Id = 61,
                            CityId = 2,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)26,
                            RainChance = (byte)31,
                            TempC = 4.4m,
                            TempF = 36.4m,
                            Wind = 10.3m
                        },
                        new
                        {
                            Id = 62,
                            CityId = 2,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)16,
                            RainChance = (byte)51,
                            TempC = -39.0m,
                            TempF = -7.0m,
                            Wind = 5.2m
                        },
                        new
                        {
                            Id = 63,
                            CityId = 2,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)32,
                            RainChance = (byte)12,
                            TempC = -17.9m,
                            TempF = 14.1m,
                            Wind = 7.7m
                        },
                        new
                        {
                            Id = 64,
                            CityId = 2,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)51,
                            RainChance = (byte)50,
                            TempC = 44.1m,
                            TempF = 76.1m,
                            Wind = 1.8m
                        },
                        new
                        {
                            Id = 65,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)18,
                            RainChance = (byte)39,
                            TempC = -21.4m,
                            TempF = 10.6m,
                            Wind = 19.9m
                        },
                        new
                        {
                            Id = 66,
                            CityId = 3,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)47,
                            RainChance = (byte)86,
                            TempC = 22.3m,
                            TempF = 54.3m,
                            Wind = 19.9m
                        },
                        new
                        {
                            Id = 67,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)26,
                            RainChance = (byte)37,
                            TempC = -25.1m,
                            TempF = 6.9m,
                            Wind = 10.6m
                        },
                        new
                        {
                            Id = 68,
                            CityId = 3,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)79,
                            RainChance = (byte)75,
                            TempC = 43.2m,
                            TempF = 75.2m,
                            Wind = 3.3m
                        },
                        new
                        {
                            Id = 69,
                            CityId = 3,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)62,
                            RainChance = (byte)18,
                            TempC = -32.8m,
                            TempF = -0.8m,
                            Wind = 15.2m
                        },
                        new
                        {
                            Id = 70,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)26,
                            RainChance = (byte)38,
                            TempC = 40.4m,
                            TempF = 72.4m,
                            Wind = 5.7m
                        },
                        new
                        {
                            Id = 71,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)75,
                            RainChance = (byte)4,
                            TempC = 25.9m,
                            TempF = 57.9m,
                            Wind = 10.9m
                        },
                        new
                        {
                            Id = 72,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)6,
                            RainChance = (byte)82,
                            TempC = 26.0m,
                            TempF = 58.0m,
                            Wind = 17.5m
                        },
                        new
                        {
                            Id = 73,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)47,
                            RainChance = (byte)2,
                            TempC = 24.8m,
                            TempF = 56.8m,
                            Wind = 10.5m
                        },
                        new
                        {
                            Id = 74,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)99,
                            RainChance = (byte)23,
                            TempC = 10.5m,
                            TempF = 42.5m,
                            Wind = 0.1m
                        },
                        new
                        {
                            Id = 75,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)80,
                            RainChance = (byte)3,
                            TempC = 44.0m,
                            TempF = 76.0m,
                            Wind = 6.1m
                        },
                        new
                        {
                            Id = 76,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)21,
                            RainChance = (byte)18,
                            TempC = 0.3m,
                            TempF = 32.3m,
                            Wind = 1.2m
                        },
                        new
                        {
                            Id = 77,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)12,
                            RainChance = (byte)32,
                            TempC = 35.6m,
                            TempF = 67.6m,
                            Wind = 3.9m
                        },
                        new
                        {
                            Id = 78,
                            CityId = 3,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)5,
                            RainChance = (byte)69,
                            TempC = -42.1m,
                            TempF = -10.1m,
                            Wind = 7.7m
                        },
                        new
                        {
                            Id = 79,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)62,
                            RainChance = (byte)7,
                            TempC = -30.5m,
                            TempF = 1.5m,
                            Wind = 4.1m
                        },
                        new
                        {
                            Id = 80,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)38,
                            RainChance = (byte)28,
                            TempC = 8.2m,
                            TempF = 40.2m,
                            Wind = 1.3m
                        },
                        new
                        {
                            Id = 81,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)63,
                            RainChance = (byte)47,
                            TempC = 46.1m,
                            TempF = 78.1m,
                            Wind = 4.7m
                        },
                        new
                        {
                            Id = 82,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)20,
                            RainChance = (byte)29,
                            TempC = 23.9m,
                            TempF = 55.9m,
                            Wind = 19.9m
                        },
                        new
                        {
                            Id = 83,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)96,
                            RainChance = (byte)3,
                            TempC = -44.8m,
                            TempF = -12.8m,
                            Wind = 7.6m
                        },
                        new
                        {
                            Id = 84,
                            CityId = 3,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)56,
                            RainChance = (byte)55,
                            TempC = -33.0m,
                            TempF = -1.0m,
                            Wind = 17.2m
                        },
                        new
                        {
                            Id = 85,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)7,
                            RainChance = (byte)0,
                            TempC = -4.9m,
                            TempF = 27.1m,
                            Wind = 15.7m
                        },
                        new
                        {
                            Id = 86,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)2,
                            RainChance = (byte)1,
                            TempC = -25.2m,
                            TempF = 6.8m,
                            Wind = 14.2m
                        },
                        new
                        {
                            Id = 87,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)80,
                            RainChance = (byte)71,
                            TempC = 33.1m,
                            TempF = 65.1m,
                            Wind = 9.5m
                        },
                        new
                        {
                            Id = 88,
                            CityId = 3,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)89,
                            RainChance = (byte)90,
                            TempC = 50.0m,
                            TempF = 82.0m,
                            Wind = 11.2m
                        },
                        new
                        {
                            Id = 89,
                            CityId = 3,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)22,
                            RainChance = (byte)57,
                            TempC = 31.5m,
                            TempF = 63.5m,
                            Wind = 16.4m
                        },
                        new
                        {
                            Id = 90,
                            CityId = 3,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)39,
                            RainChance = (byte)98,
                            TempC = 35.2m,
                            TempF = 67.2m,
                            Wind = 17.4m
                        },
                        new
                        {
                            Id = 91,
                            CityId = 3,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)72,
                            RainChance = (byte)86,
                            TempC = 28.3m,
                            TempF = 60.3m,
                            Wind = 4.2m
                        },
                        new
                        {
                            Id = 92,
                            CityId = 3,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)87,
                            RainChance = (byte)36,
                            TempC = 6.0m,
                            TempF = 38.0m,
                            Wind = 19.6m
                        },
                        new
                        {
                            Id = 93,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)11,
                            RainChance = (byte)7,
                            TempC = -38.9m,
                            TempF = -6.9m,
                            Wind = 13.6m
                        },
                        new
                        {
                            Id = 94,
                            CityId = 3,
                            Condition = 5,
                            Date = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)35,
                            RainChance = (byte)42,
                            TempC = -40.9m,
                            TempF = -8.9m,
                            Wind = 9.0m
                        },
                        new
                        {
                            Id = 95,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)3,
                            RainChance = (byte)49,
                            TempC = 49.6m,
                            TempF = 81.6m,
                            Wind = 0.0m
                        },
                        new
                        {
                            Id = 96,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)11,
                            RainChance = (byte)71,
                            TempC = -29.8m,
                            TempF = 2.2m,
                            Wind = 18.5m
                        },
                        new
                        {
                            Id = 97,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)63,
                            RainChance = (byte)77,
                            TempC = -15.4m,
                            TempF = 16.6m,
                            Wind = 9.8m
                        },
                        new
                        {
                            Id = 98,
                            CityId = 4,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)55,
                            RainChance = (byte)81,
                            TempC = 4.7m,
                            TempF = 36.7m,
                            Wind = 2.1m
                        },
                        new
                        {
                            Id = 99,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)56,
                            RainChance = (byte)32,
                            TempC = 41.1m,
                            TempF = 73.1m,
                            Wind = 6.7m
                        },
                        new
                        {
                            Id = 100,
                            CityId = 4,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)66,
                            RainChance = (byte)90,
                            TempC = -16.5m,
                            TempF = 15.5m,
                            Wind = 14.1m
                        },
                        new
                        {
                            Id = 101,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)6,
                            RainChance = (byte)70,
                            TempC = -15.7m,
                            TempF = 16.3m,
                            Wind = 0.7m
                        },
                        new
                        {
                            Id = 102,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)98,
                            RainChance = (byte)64,
                            TempC = -2.7m,
                            TempF = 29.3m,
                            Wind = 15.0m
                        },
                        new
                        {
                            Id = 103,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)6,
                            RainChance = (byte)71,
                            TempC = -7.0m,
                            TempF = 25.0m,
                            Wind = 6.1m
                        },
                        new
                        {
                            Id = 104,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)96,
                            RainChance = (byte)97,
                            TempC = -28.4m,
                            TempF = 3.6m,
                            Wind = 3.0m
                        },
                        new
                        {
                            Id = 105,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)30,
                            RainChance = (byte)71,
                            TempC = 3.1m,
                            TempF = 35.1m,
                            Wind = 0.7m
                        },
                        new
                        {
                            Id = 106,
                            CityId = 4,
                            Condition = 5,
                            Date = new DateTime(2022, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)41,
                            RainChance = (byte)41,
                            TempC = -35.0m,
                            TempF = -3.0m,
                            Wind = 9.7m
                        },
                        new
                        {
                            Id = 107,
                            CityId = 4,
                            Condition = 2,
                            Date = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)2,
                            RainChance = (byte)93,
                            TempC = -33.5m,
                            TempF = -1.5m,
                            Wind = 11.3m
                        },
                        new
                        {
                            Id = 108,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)48,
                            RainChance = (byte)65,
                            TempC = 9.2m,
                            TempF = 41.2m,
                            Wind = 1.8m
                        },
                        new
                        {
                            Id = 109,
                            CityId = 4,
                            Condition = 1,
                            Date = new DateTime(2022, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)81,
                            RainChance = (byte)93,
                            TempC = 0.3m,
                            TempF = 32.3m,
                            Wind = 4.3m
                        },
                        new
                        {
                            Id = 110,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)49,
                            RainChance = (byte)6,
                            TempC = 12.3m,
                            TempF = 44.3m,
                            Wind = 6.2m
                        },
                        new
                        {
                            Id = 111,
                            CityId = 4,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)4,
                            RainChance = (byte)63,
                            TempC = -38.8m,
                            TempF = -6.8m,
                            Wind = 2.6m
                        },
                        new
                        {
                            Id = 112,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)22,
                            RainChance = (byte)55,
                            TempC = -18.1m,
                            TempF = 13.9m,
                            Wind = 6.0m
                        },
                        new
                        {
                            Id = 113,
                            CityId = 4,
                            Condition = 0,
                            Date = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)84,
                            RainChance = (byte)3,
                            TempC = 7.5m,
                            TempF = 39.5m,
                            Wind = 14.3m
                        },
                        new
                        {
                            Id = 114,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)1,
                            RainChance = (byte)23,
                            TempC = 21.4m,
                            TempF = 53.4m,
                            Wind = 4.0m
                        },
                        new
                        {
                            Id = 115,
                            CityId = 4,
                            Condition = 2,
                            Date = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)6,
                            RainChance = (byte)63,
                            TempC = -40.5m,
                            TempF = -8.5m,
                            Wind = 19.0m
                        },
                        new
                        {
                            Id = 116,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)48,
                            RainChance = (byte)58,
                            TempC = 1.6m,
                            TempF = 33.6m,
                            Wind = 12.8m
                        },
                        new
                        {
                            Id = 117,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)12,
                            RainChance = (byte)84,
                            TempC = -43.6m,
                            TempF = -11.6m,
                            Wind = 14.8m
                        },
                        new
                        {
                            Id = 118,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)90,
                            RainChance = (byte)42,
                            TempC = 13.6m,
                            TempF = 45.6m,
                            Wind = 2.6m
                        },
                        new
                        {
                            Id = 119,
                            CityId = 4,
                            Condition = 1,
                            Date = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)27,
                            RainChance = (byte)62,
                            TempC = -49.2m,
                            TempF = -17.2m,
                            Wind = 10.4m
                        },
                        new
                        {
                            Id = 120,
                            CityId = 4,
                            Condition = 3,
                            Date = new DateTime(2022, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)23,
                            RainChance = (byte)91,
                            TempC = 44.3m,
                            TempF = 76.3m,
                            Wind = 0.6m
                        },
                        new
                        {
                            Id = 121,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)51,
                            RainChance = (byte)9,
                            TempC = 28.8m,
                            TempF = 60.8m,
                            Wind = 7.3m
                        },
                        new
                        {
                            Id = 122,
                            CityId = 4,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)74,
                            RainChance = (byte)95,
                            TempC = 20.8m,
                            TempF = 52.8m,
                            Wind = 8.0m
                        },
                        new
                        {
                            Id = 123,
                            CityId = 4,
                            Condition = 4,
                            Date = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)97,
                            RainChance = (byte)0,
                            TempC = -33.5m,
                            TempF = -1.5m,
                            Wind = 9.6m
                        },
                        new
                        {
                            Id = 124,
                            CityId = 4,
                            Condition = 0,
                            Date = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Humidity = (byte)4,
                            RainChance = (byte)88,
                            TempC = -12.8m,
                            TempF = 19.2m,
                            Wind = 7.0m
                        });
                });

            modelBuilder.Entity("Api.Entities.City", b =>
                {
                    b.HasOne("Api.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Api.Entities.Weather", b =>
                {
                    b.HasOne("Api.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
